### PR TITLE
Fix for extra victories being counted in tiebreaker points.

### PR DESCRIPTION
**Pull request by neilself**
Fix for extra victories being counted in tiebreaker points.

### CODE REVIEW

**Comment by neilself** [comment]
There's probably a more elegant place to put it in but I think this one works.

The extra victories only matter for tiebreaker points, and the remove_extra_victories() function appears to be idempotent so it doesn't matter if it gets called repeatedly.

**Comment by statico** [comment]
Thanks! We'll try this on staging soon.

**Comment by ntucker** [comment]
You might try adding another receiver like the one that calls that function:

@receiver(post_save, sender=Match, dispatch_uid="remove_extra_victories")
def remove_extra_victories(sender, instance, created, **kwargs):
instance.remove_extra_victories()

**Comment by neilself** [comment]
I suggest we do whatever Nathaniel says. I know nothing about django so I stuck with the simplest possible solution that looked like it would work and not horribly break anything else.

**Comment by neilself** [comment]
After noticing that it looks like this change is live on the website on some level, but that it only works for extra wins and not extra losses, I have updated my pull request (I think) to remove those extra losses.

**Pull request merged**
